### ISSUE TITLE
Need a new tag and release v2.0.2

### ISSUE THREAD

**Issue by agsole-asapp** [aymerick/raymond#24]
Tag v2.0.1 does not match latest in master. Would it be possible for you to do a tag

I'm Using [dep](https://github.com/golang/dep) which uses tags

**Comment by razorness** [comment]
As you can see ... last commit is two years old. Set `branch = "master"` to get current master instead of tag.

**Comment by aymerick** [comment]
You are right, it is time to create a new tag :) I will do that today

**Comment by aymerick** [comment]
Done 🎉
