### ISSUE TITLE
Go get problems with submodule mustache

### ISSUE THREAD

**Issue by kataras** [aymerick/raymond#4]
Hello @aymerick , I recently add built'n support for your template engine into [Iris](https://github.com/kataras/iris) and I have some reports from its users, take a look [here](https://github.com/kataras/iris/issues/249).

This is the error from go get (as they said): 

```
# cd /Users/ehlertm/wt/go/src/github.com/aymerick/raymond; git submodule update --init --recursive
Cloning into '/Users/ehlertm/wt/go/src/github.com/aymerick/raymond/mustache'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out

fatal: clone of 'git://github.com/mustache/spec.git' into submodule path '/Users/ehlertm/wt/go/src/github.com/aymerick/raymond/mustache' failed
package github.com/aymerick/raymond: exit status 128

```

I personally, installed this today and I hadn't this issue, but I think it will be better to remove the mustache submodule from this repository, you don't need it as submodule ( I think)

**Comment by aymerick** [comment]
Thanks for the report.

As far as I understand, your user had a network conf issue, right ?

So I close that issue.
