### ISSUE TITLE
Block helpers as HTML attributes

### ISSUE THREAD

**Issue by maxhoffmann** [aymerick/raymond#7]
I’ve run into a bug where the parser throws an error rendering any other helper than `{{value}}` as HTML attributes:

```
Parse error on line 7:\nExpecting Close, got: 'Equals{\"=\"}'
```

**Minimal Example**

``` html
<h1 {{add 1 2}}>
```

**Actual use case**

``` html
<option value="test" {{equals value "test"}}selected{{/equals}}>Test</option>
```

``` go
template.RegisterHelper("equals", func(variable string, comparator string, options *raymond.Options) raymond.SafeString {
    if variable == comparator {
        return raymond.SafeString(options.Fn())
    } else {
        return raymond.SafeString("")
    }
})
```

Using helpers for rendering HTML attributes seems to be supported by handlebars, e.g. http://stackoverflow.com/questions/9917705/setting-the-selected-value-of-a-select-element-in-handlebars.

**Comment by aymerick** [comment]
I added the `equal` helper to help you.

See the doc here: <https://github.com/aymerick/raymond#the-equal-helper>

FYI here is the implementation: <https://github.com/aymerick/raymond/blob/master/helper.go#L374>
